### ISSUE TITLE
Edabit solution repository, Create more issue for problem task

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#1]
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py

- [ ]  In file there should be problem statement and link to probelm
    example - 
```cpp
/* this program will add two numbers
    * Problem : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020
Good Luck,

**Comment by subramanian0** [comment]
can i work on this?

**Comment by aayushi-droid** [comment]
ya sure @subramanian0 assigned, Take care of all suggestions before making PR

**Comment by aayushi-droid** [comment]
@subramanian0 Everyone can work on this issue

**Problem Task** - You have to make issues in repo using issue template. 
find issue on https:://edabit.com

**Comment by Manoj13-coder** [comment]
I want to contribute

**Comment by Manoj13-coder** [comment]
may i move ahead for this ?
