### ISSUE TITLE
Reverse Coding Challenge in Cpp

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#10]
Before jumping into Pr first comment for assign.

**Problem statement:** This is a reverse coding challenge. Normally you're given explicit directions with how to create a function. Here, you must generate your own function to satisfy the relationship between the inputs and outputs.

Your task is to create a function that, when fed the inputs below, produce the sample outputs shown.
**Probelm Link:** https://edabit.com/challenge/64CeZWx5wWhTxhHLL

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Rubix982** [comment]
Sure. 
Just a question about the problem. Is this asking for a hard-coded implementation to the solution, or is it asking for finding a function that finds out the mathematical relation between the inputs -> outputs?

**Comment by Rubix982** [comment]
Nevermind, it's trying to do the latter. Can I have this?

**Comment by aayushi-droid** [comment]
I didn't get the relation between Input and output for the given problem, So I added here.

**Comment by aayushi-droid** [comment]
@Rubix982 Assigned,

**Comment by Rubix982** [comment]
Thanks, @aayushi-droid , I was just wondering what folder to put my solution in.
