### ISSUE TITLE
Less Than or Equal To 0

### ISSUE THREAD

**Issue by ghost** [aayushi-droid/Edabit-Solutions#102]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes a number as its only argument and returns true if it's less than or equal to zero, otherwise return false.
**Problem Link** : https://edabit.com/challenge/7KFAJSSp3pmE8bHhK
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : very easy

---
Before submitting a PR please Check some details.

- [ ] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck

**Comment by ghost** [comment]
Please let me work on this problem!

**Comment by meta-crusher** [comment]
@devansh-pratap-singh can u assign this to me?

**Comment by uchihacoder** [comment]
i can help

**Comment by NidhiNivedita6** [comment]
Please assign me this.
