### ISSUE TITLE
Sum of Cubes

### ISSUE THREAD

**Issue by Vrindagupta6828** [aayushi-droid/Edabit-Solutions#104]
**Problem statement** :Take an array of integers (positive or negative or both) and return the sum of the absolute value of each element.

**Problem Link** : https://edabit.com/challenge/XdAR3KohR5w7rjrFg

**Choose one Category** - Easy

**question category** : arrays, algebra, geometry, loops, math

**Note** : If given an empty array, return 0.
---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/XdAR3KohR5w7rjrFg
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Vrindagupta6828** [comment]
please assign this issue to me

**Comment by dev-abir** [comment]
I can do this

**Comment by viswa5427** [comment]
Please assign to this to me

**Comment by Vrindagupta6828** [comment]
this will not be considered as you should have asked for assignment of the issue first

**Comment by Vrindagupta6828** [comment]
@viswa5427  please create your own issue

**Comment by NidhiNivedita6** [comment]
Please assign me this.
