### ISSUE TITLE
Letters Shared Between Two Words

### ISSUE THREAD

**Issue by ashishrrs** [aayushi-droid/Edabit-Solutions#105]
Before jumping into Pr first comment for assign.

**Problem statement** :Create a function that returns the number of characters shared between two words.
**Probelm Link** : https://edabit.com/challenge/qeCS48GXtK9NJLc9C
**Choose one Cateorgy** - Hard
**question category** : arrays , strings

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jineshparakh** [comment]
Can you please assign this to me!
I want to contribute

**Comment by meta-crusher** [comment]
@ashishrrs can u assign this to me?
