### ISSUE TITLE
How Many Days Between Two Dates

### ISSUE THREAD

**Issue by Halix267** [aayushi-droid/Edabit-Solutions#106]
Before jumping into Pr first comment for assign.

**Problem statement** :Create a function that takes two dates and returns the number of days between the first and second date.
**Probelm Link** : https://edabit.com/challenge/3hdXjfJozQySRC3gE
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Hard

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "hard"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will give the days between two dates
 * Problem Link : https://edabit.com/challenge/3hdXjfJozQySRC3gE
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Halix267** [comment]
Can I work on this issue.

**Comment by viren-vii** [comment]
Can I get this task?

**Comment by mallickarpit** [comment]
i can give it a shot

**Comment by RAJAT-SOUL** [comment]
I would like to give the c++ approach to this question.
