### ISSUE TITLE
Find the GCD of two number ?

### ISSUE THREAD

**Issue by vamsireddy22** [aayushi-droid/Edabit-Solutions#11]
Before jumping into Pr first comment for assign.

**Problem statement:** Find the GCD of two number ?
**Probelm Link:** https://edabit.com/challenge/BzEQsTSmPATbsZJCR 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by aayushi-droid** [comment]
- [ ✔️] Task Assigned

@vamsireddy22

**Comment by vamsireddy22** [comment]
Hey, hi I have made my pull requests. Kindly got through it and merge them.

Thanks and regards
Vamsi
