### ISSUE TITLE
Find the Missing Number

### ISSUE THREAD

**Issue by pranav230** [aayushi-droid/Edabit-Solutions#112]
Before jumping into Pr first comment for assign.

**Problem statement** : Find the Missing Number
**Probelm Link** : https://edabit.com/challenge/7YaJhC4terApw5DFa
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : Create a function that takes an array of numbers between 1 and 10 (excluding one number) and returns the missing number.
 * Problem Link : https://edabit.com/challenge/7YaJhC4terApw5DFa
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by pranav230** [comment]
@aayushi-droid  please assign this to me

**Comment by VaderX** [comment]
Can you assign this to me?

**Comment by meta-crusher** [comment]
@pranav230 can u assign this to me

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by zahinekbal** [comment]
@pranav230 can you assign this to me ....
i am working on this issues ,I will create PR soon

**Comment by yasharth291** [comment]
can you please assign this to me

**Comment by zahinekbal** [comment]
@pranav230 I Added FindMissingNumber.cpp ..
please check my code and review my PR

**Comment by aayushi-droid** [comment]
PR of assign Person will review.. sorry
