### ISSUE TITLE
Convert a Number to Base-2

### ISSUE THREAD

**Issue by KhushiGangopadhyay** [aayushi-droid/Edabit-Solutions#113]
Before jumping into Pr first comment for assign.

**Problem statement** :Create a function that returns a base-2 (binary) representation of a base-10 (decimal) string number.
**Probelm Link** : https://edabit.com/challenge/3kcrnpHk7krNZdnKK
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by KhushiGangopadhyay** [comment]
please assign this to me

**Comment by NidhiNivedita6** [comment]
Please assign me this.
