### ISSUE TITLE
Equality of Three Numbers

### ISSUE THREAD

**Issue by ghost** [aayushi-droid/Edabit-Solutions#114]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes three integer arguments (a, b, c) and returns the amount of integers which are of equal value.
**Problem Link** : https://edabit.com/challenge/wujqD4xbL7X5Bzd5e
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : easy

---
Before submitting a PR please Check some details.

- [ ] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
I would like to work on this problem.

**Comment by Nikhil-1503** [comment]
Assign this to me

**Comment by meta-crusher** [comment]
can u assign this ques to me?

**Comment by SMITVASOYA** [comment]
can I solve it?

**Comment by visu123456** [comment]
I can solve it with set..let me do it

**Comment by pranavgoel29** [comment]
Assign this issue to me. I will make a PR within five minutes after you assign it to me.

**Comment by NidhiNivedita6** [comment]
Please assign me this.
