### ISSUE TITLE
Maximum Edge of a Triangle

### ISSUE THREAD

**Issue by Harshit564** [aayushi-droid/Edabit-Solutions#118]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that finds the maximum range of a triangle's third edge, where the side lengths are all integers.
**Probelm Link** :  https://edabit.com/challenge/56XXwAkLJGbEccYfn
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Harshit564** [comment]
Please assign this issue to me!

**Comment by charchitmangal** [comment]
Hello! I would like to work on this

**Comment by Harshit564** [comment]
> Hello! I would like to work on this

You have make your own issue and then make a PR.

**Comment by nssk1999** [comment]
@Harshit564 can you assign the issue to me I just solved it

**Comment by Harshit564** [comment]
> @Harshit564 can you assign the issue to me I just solved it

They will assign after u make your own issue.
