### ISSUE TITLE
Solution for Burrrp!

### ISSUE THREAD

**Issue by ghost** [aayushi-droid/Edabit-Solutions#120]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that returns the string "Burp" with the amount of "r's" determined by the input parameters of the function.
**Problem Link** : https://edabit.com/challenge/vxpP4nnDhRr2Yc3Lo
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : easy

---
Before submitting a PR please Check some details.

- [ ] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
I would like to work on this problem!

**Comment by sohan-naidu** [comment]
Hello! Is it okay if I work on this problem too?

**Comment by NidhiNivedita6** [comment]
Please assign me this.
