### ISSUE TITLE
Solution for Eliminate odd numbers from an array

### ISSUE THREAD

**Issue by mrigankdembla** [aayushi-droid/Edabit-Solutions#126]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes an array of numbers and returns only the even values.
**Probelm Link** : https://edabit.com/challenge/7iT6DbY3GsHnLBPq4
**Choose one Cateorgy** - Easy
**question category** : Arrays

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by mrigankdembla** [comment]
I would like to work on this problem.

**Comment by mrigankdembla** [comment]
#127 added the solution, please review.

**Comment by dhavalmaniyar** [comment]
please assign this task to me.
