### ISSUE TITLE
Write a function to check Multiple of 100

### ISSUE THREAD

**Issue by nssk1999** [aayushi-droid/Edabit-Solutions#128]
### Create a function that takes an integer and return true if it's divisible by 100, otherwise return false.

Before jumping into Pr first comment for assign.

**Problem statement** :Create a function that takes an integer and return true if it's divisible by 100, otherwise return false.
**Probelm Link** : https://edabit.com/challenge/qMr6wYGr6NaXAPQGF
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by js0805** [comment]
please assign this to me.

**Comment by nssk1999** [comment]
you need to create your own issue to get it assigned .

**Comment by namanb99** [comment]
Assign this to me

**Comment by 23krishna** [comment]
please assign

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by Mayankjha997** [comment]
hey i like to work on this

**Comment by nssk1999** [comment]
> please assign this to me.
> hey i like to work on this
> Please assign me this.
> please assign

the repo organizers assign the issue mostly to the person who created it
check more about it at the first issue pinned up
Edabit solution repository, Create more issue for problem task #1

**Comment by nssk1999** [comment]
@aayushi-droid plz assign the issue to me
