### ISSUE TITLE
Double Character Swap

### ISSUE THREAD

**Issue by chiru-cd** [aayushi-droid/Edabit-Solutions#129]
Before jumping into Pr first comment for assign.

**Problem statement** : Write a function to replace all instances of character c1 with character c2 and vice versa.
**Probelm Link** : https://edabit.com/challenge/s695FkhRd3J65tmdQ
**Choose one Cateorgy** - Medium
**question category** : Strings

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by chiru-cd** [comment]
I would like to work on this issue. Please assign.

**Comment by Madhur215** [comment]
I am ready to work on it. Please assign.

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by Mayankjha997** [comment]
I would like to work on this issue. Please assign.
