### ISSUE TITLE
Reminder from two numbers

### ISSUE THREAD

**Issue by js0805** [aayushi-droid/Edabit-Solutions#131]
Before jumping into Pr first comment for assign.

**Problem statement** :Return the Remainder from Two Numbers
**Probelm Link** : https://edabit.com/challenge/bTrM8t39vjrAtYytA
**Choose one Cateorgy** - Very Easy
**question category** : Maths,numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* this program will add two numbers
 * Problem : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
 * Choose one Cateorgy - very easy
 * question category : math,numbers
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by js0805** [comment]
Please assign me this issue.

**Comment by Madhur215** [comment]
Please assign this to me.

**Comment by js0805** [comment]
> Please assign this to me.

Please make new issue.

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by offi-ani** [comment]
Can i take up on this?Can you please assign me this

**Comment by mrinal07** [comment]
Please assign this task to me!
I will follow each and every guideline properly.
