### ISSUE TITLE
Stuttering Function

### ISSUE THREAD

**Issue by Aditi-1400** [aayushi-droid/Edabit-Solutions#132]
Before jumping into Pr first comment for assign.

**Problem statement** : ### 
> Write a function that stutters a word as if someone is struggling to read it. The first two letters are repeated twice with an ellipsis ... and space after each, and then the word is pronounced with a question mark ?.
> stutter("incredible") ➞ "in... in... incredible?"
> 
> stutter("enthusiastic") ➞ "en... en... enthusiastic?"
> 
> stutter("outstanding") ➞ "ou... ou... outstanding?"

**Probelm Link** : [https://edabit.com/challenge/gt9LLufDCMHKMioh2]
**Choose one Cateorgy** -  Easy 
**question category** : Algorithms, formatting

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Aditi-1400** [comment]
Hey I would Like to work on this issue

**Comment by mrigankdembla** [comment]
@Aditi-1400  can you please let me know if the labels are getting auto assigned or steps by which we can add it ?

**Comment by Aditi-1400** [comment]
They are getting auto assigned.

**Comment by mrigankdembla** [comment]
yeah, but I'm not able to see it on my issue.

**Comment by Aditi-1400** [comment]
@aayushi-droid I had a small doubt, The code is supposed to be in Python or C++?
