### ISSUE TITLE
Name Greeting! in cpp

### ISSUE THREAD

**Issue by nssk1999** [aayushi-droid/Edabit-Solutions#136]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes a name and returns a greeting in the form of a string.
**Probelm Link** : https://edabit.com/challenge/MtG39AgXhyeePSiY2
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by nssk1999** [comment]
I am would be happy if the issue is assigned to me 😊😊😉😎

**Comment by Pranjal81** [comment]
I like to solve this issue, please assign this task to me.

**Comment by devdoesgit** [comment]
I'll be more than happy to contribute

**Comment by rsrahul1000** [comment]
Please assign this to me, I'd love to solve this

**Comment by nssk1999** [comment]
> I like to solve this issue, please assign this task to me.
the repo organizers assign the issue mostly to the person who created it
check more about it at the first issue pinned up
Edabit solution repository, Create more issue for problem task #1

**Comment by nssk1999** [comment]
> I like to solve this issue, please assign this task to me.


> I'll be more than happy to contribute

the repo organizers assign the issue mostly to the person who created it
check more about it at the first issue pinned up
Edabit solution repository, Create more issue for problem task #1

**Comment by Maitreyi88** [comment]
This is simple. I can do it.

**Comment by nssk1999** [comment]
> This is simple. I can do it.

the repo organizers assign the issue mostly to the person who created it
check more about it at the first issue pinned up
Edabit solution repository, Create more issue for problem task #1

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by Mayankjha997** [comment]
hey! i would like to contribute plzz assign it

**Comment by nssk1999** [comment]
> Please assign me this.
> 

the repo organizers assign the issue mostly to the person who created it
check more about it at the first issue pinned up
Edabit solution repository, Create more issue for problem task #1

**Comment by nssk1999** [comment]
> hey! i would like to contribute plzz assign it

the repo organizers assign the issue mostly to the person who created it
check more about it at the first issue pinned up
Edabit solution repository, Create more issue for problem task #1
