### ISSUE TITLE
Staircase Of Recursion

### ISSUE THREAD

**Issue by Madhur215** [aayushi-droid/Edabit-Solutions#138]
Before jumping into Pr first comment for assign.

**Problem statement**: Write a function that returns the number of ways a person can climb n stairs, where the person may only climb 1 or 2 steps at a time.
**Problem Link**:  https://edabit.com/challenge/JR3T5o6PwzvuGnRge
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Madhur215** [comment]
Please assign it to me.

**Comment by Spyy004** [comment]
Assign it to me please

**Comment by princekalra** [comment]
hey can i contribute on this
