### ISSUE TITLE
Letter Distance in cpp

### ISSUE THREAD

**Issue by gourav-j** [aayushi-droid/Edabit-Solutions#139]
Before jumping into Pr first comment for assign.

**Problem statement** : Given two words, the letter distance is calculated by taking the absolute value of the difference in character codes and summing up the difference.

If one word is longer than another, add the difference in lengths towards the score.

To illustrate:

letterDistance("house", "fly") = dist("h", "f") + dist("o", "l") + dist("u", "y") + dist(house.length, fly.length)

= |104 - 102| + |111 - 108| + |117 - 121| + |5 - 3|
= 2 + 3 + 4 + 2
= 11
**Probelm Link** : https://edabit.com/challenge/5Xo5fBrQui9opFWH5
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Hard

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gourav-j** [comment]
Please assign this to me

**Comment by nancyanand2807** [comment]
Please assign this to me

**Comment by mahnotrohan** [comment]
I'd like to work on this, please assign
