### ISSUE TITLE
Add up the Numbers from a Single Number

### ISSUE THREAD

**Issue by jayanthjj** [aayushi-droid/Edabit-Solutions#14]
Before jumping into Pr first comment for assign.

**Create a function that takes a number as an argument. Add up all the numbers from 1 to the number you passed to the function.** :
**https://edabit.com/challenge/XDx6JoaumAimRHgEt** : 
**Choose one Cateorgy** - Easy
**question category** : Numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
@aayushi-droid can I work on this?

**Comment by aayushi-droid** [comment]
- [ ✔️] Task Assigned @jayanthj737

**Comment by jayanthjj** [comment]
@aayushi-droid Added addUp #53
