### ISSUE TITLE
Solution for Broken Bridges

### ISSUE THREAD

**Issue by mrigankdembla** [aayushi-droid/Edabit-Solutions#140]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function which validates whether a bridge is safe to walk on (i.e. has no gaps in it to fall through).
**Probelm Link** : https://edabit.com/challenge/udrQ2ckXP9cXNXiSk
**Choose one Cateorgy** - Easy
**question category** : Strings,Validation

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by codetravellearn** [comment]
i would like contribute

**Comment by mrigankdembla** [comment]
I would like to contribute

**Comment by mrigankdembla** [comment]
Solution provided, please review and merge: #149
