### ISSUE TITLE
Find The Odd Integer

### ISSUE THREAD

**Issue by vaghelaparth05** [aayushi-droid/Edabit-Solutions#141]
Problem statement : Create a function that takes an array and finds the integer which appears an odd number of times.
Problem Link : https://edabit.com/challenge/wgnmQTbfssuhvZHqe
Difficulty : Hard
Category : Implementation

**Comment by vaghelaparth05** [comment]
I have already solved the question. Please this to me.

**Comment by Codedude1** [comment]
Wanna work

**Comment by vaghelaparth05** [comment]
Yes

**Comment by ashandilya** [comment]
wanna solve this

**Comment by sachdevarobin** [comment]
I would like to solve this

**Comment by ayushi-get** [comment]
i would like to solve this to .

**Comment by Spyy004** [comment]
Hey, I would like to solve this issue

**Comment by NidhiNivedita6** [comment]
I would like to solve this.

**Comment by anujjain5699** [comment]
Hey, I would like to solve this issue
