### ISSUE TITLE
Prime Factors with Sum

### ISSUE THREAD

**Issue by devdoesgit** [aayushi-droid/Edabit-Solutions#145]
Before jumping into Pr first comment for assign.

**Problem statement** : Prime Factors with Sum
**Probelm Link** :  https://edabit.com/challenge/Ch9a2fsTckkdE26XX
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Expert

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/Ch9a2fsTckkdE26XX
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by devdoesgit** [comment]
Please assign this problem to me!

**Comment by Aakansha99** [comment]
@andrewflik kindly assign this issue to me

**Comment by Aakansha99** [comment]
kindly assign this issue to me

**Comment by devdoesgit** [comment]
hey @Aakansha99 usually the issue is assigned to the person who opens it, so kindly refer to #1

**Comment by Mayankjha997** [comment]
kindly assign this issue to me

**Comment by devdoesgit** [comment]
Kindly review the PR #204
