### ISSUE TITLE
Absolute Sum

### ISSUE THREAD

**Issue by Aakansha99** [aayushi-droid/Edabit-Solutions#147]
Before jumping into Pr first comment for assign.

**Problem statement** :Absolute Sum
**Probelm Link** : https://edabit.com/challenge/jBFpjEG3tvsjTZbD4
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by saurabhatram** [comment]
Can I please solve this problem

**Comment by wimanshaherath** [comment]
I would like to contribute to this. Please assign me to this problem.

**Comment by ayushi-get** [comment]
i would like to solve this issue . please allow !!

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by Aditi0707** [comment]
please assign this issue to me

**Comment by princekalra** [comment]
hey can i contribute on this

**Comment by Taher232** [comment]
ok

**Comment by Taher232** [comment]
ok
