### ISSUE TITLE
Is the Number Less than or Equal to Zero?

### ISSUE THREAD

**Issue by amreenabbas** [aayushi-droid/Edabit-Solutions#156]
Before jumping into Pr first comment for assign.

**Problem statement** : Is the Number Less than or Equal to Zero?
**Probelm Link** : https://edabit.com/challenge/7KFAJSSp3pmE8bHhK
**Choose one Cateorgy** - Very Easy
**question category** : conditions, language_fundamentals, validation

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by amreenabbas** [comment]
I want to work over this issue. Please assign this to me.

**Comment by srivathsa729** [comment]
take

**Comment by ShravyaMallya** [comment]
I'd like to work on this. Could you please assign this issue to me?

**Comment by Nikhil-1503** [comment]
Please assign this to me.

**Comment by wimanshaherath** [comment]
I like work on this. Please assign this to me.

**Comment by AviSharmaaa** [comment]
I'd like to work on this. Please assign this to me.

**Comment by NidhiNivedita6** [comment]
I would like to work on this. Please assign this to me.

**Comment by akhilbonagiri8465** [comment]
can you assign me , i would like to work on this

**Comment by anujjain5699** [comment]
**I would like to work on this. Please assign this to me.**

**Comment by Shreyaa-22** [comment]
I would like to work on it, can you assign it to me?

**Comment by princekalra** [comment]
hey can i contribute on this

**Comment by aayushi-droid** [comment]
@amreenabbas Are you working on this issue?
