### ISSUE TITLE
CPP: Number of Squares in an N * N Grid

### ISSUE THREAD

**Issue by jayanthjj** [aayushi-droid/Edabit-Solutions#16]
Before jumping into Pr first comment for assign.

**Create a function that calculates the number of different squares in an n * n square grid.** :
**https://edabit.com/challenge/ncqFJAp4bBiGwfBcg** : 
**Choose one Category** - Easy
**question category** : Math

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
@aayushi-droid Can I do this? Also the question is not available to be solved using cpp so should I try python or cpp?

**Comment by aayushi-droid** [comment]
Do you want to solve it using python then I can transfer this issue to python Repository for Edabit.

**Comment by jayanthjj** [comment]
I can do it both python and cpp. Maybe get a copy of this question for me in python too?

**Comment by aayushi-droid** [comment]
You can add in Cpp here.
for Python Check https://github.com/Py-Droid/Python-Thunder/issues

**Comment by jayanthjj** [comment]
Sure please assign either places.

**Comment by jayanthjj** [comment]
@aayushi-droid Added num Squares #57
