### ISSUE TITLE
GCD and LCM ( Part 1)

### ISSUE THREAD

**Issue by ashishrrs** [aayushi-droid/Edabit-Solutions#161]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes two numbers as arguments and returns the Greatest Common Devisor (GCD) of the two numbers.
**Probelm Link** : https://edabit.com/challenge/BzEQsTSmPATbsZJCR
**Choose one Cateorgy** - Medium 
**question category** : math ,numbers

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by SuchismitaDhal** [comment]
Hey! I am pretty well versed with C++, I would like to contribute. Can you assign this issue to me?

**Comment by khushi-gupta** [comment]
Hi, I wish to contribute. Please assign this issue to me.

**Comment by satthi153** [comment]
Hi, I would like to contribute.

**Comment by mallickarpit** [comment]
I would like to give it a shot

**Comment by anujjain5699** [comment]
Hi,I would like to contribute.
plz check my work **https://github.com/anujjain5699/cpp** in cpp and  assign this issue to me.
