### ISSUE TITLE
Count Instances of a Character in a String

### ISSUE THREAD

**Issue by 0xamitdutta** [aayushi-droid/Edabit-Solutions#179]
Before jumping into Pr first comment for assign.

**Problem statement** : Count Instances of a Character in a String
**Probelm Link** : https://edabit.com/challenge/kbFhwaDyrd79JrgeB
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Amitdutta7** [comment]
I would like to work on this problem

**Comment by mauryahimanshu** [comment]
Hey! Can you assign me this problem?

**Comment by SanskarGupta2207** [comment]
I am a competitive programmer with 2 years of experience. But I am new to open source and looking for issues involving problem solving in C++. Kindly, assign me this task.

**Comment by RAJAT-SOUL** [comment]
I would like to share the c++ approach for this question.

**Comment by dalalvarun** [comment]
I would like to work on this.

**Comment by venkateshpensalwar** [comment]
I would like to solve the problem in the C++ language for this question. please assign this task to me
