### ISSUE TITLE
Largest Swap

### ISSUE THREAD

**Issue by jayanthjj** [aayushi-droid/Edabit-Solutions#18]
Before jumping into Pr first comment for assign.

**Function that takes a two-digit number and determines if it's the largest of two possible digit swaps.** :
**Probelm Link** : https://edabit.com/challenge/mQbddasCYNTTzQEgm
**Choose one Cateorgy** - Easy
**question category** : Numbers

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
@aayushi-droid Please assign

**Comment by keshav304** [comment]
Hey @aayushi-droid can you assign me this issue?

**Comment by aayushi-droid** [comment]
- [✓]  Task assigned
@jayanthj737

**Comment by jayanthjj** [comment]
@aayushi-droid Please check #25

**Comment by aayushi-droid** [comment]
- [x]  Task Complete
