### ISSUE TITLE
Count Letters in a Word Search

### ISSUE THREAD

**Issue by mauryahimanshu** [aayushi-droid/Edabit-Solutions#181]
Before jumping into Pr first comment for assign.

**Problem statement** :  Create a function that counts the number of times a particular letter shows up in the word search.
**Probelm Link** :  https://edabit.com/challenge/bsPZtsX62zQmRHNjX
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Medium 

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Zeph-T** [comment]
@mauryahimanshu can you assign this to me?

**Comment by mahnotrohan** [comment]
I'd like to work on this, please assign this to me

**Comment by rohitbarvekar** [comment]
Hi, @mauryahimanshu . This is my first hacktoberfest request. I am interested could you please assign it to me.
