### ISSUE TITLE
Making a Box

### ISSUE THREAD

**Issue by mauryahimanshu** [aayushi-droid/Edabit-Solutions#184]
Before jumping into Pr first comment for assign.

**Problem statement** :  Create a function that creates a box based on dimension n.
**Probelm Link** :  https://edabit.com/challenge/yHeTBuJ6LDw3nhA7k
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Hard

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by nikhil121101** [comment]
hey can i contribute in java

**Comment by nikhil121101** [comment]
anyway i am happy do do it in c++ to

**Comment by aayushwadhwa1** [comment]
Hey can i contribute, i will be able to do in c++

**Comment by mauryahimanshu** [comment]
Please assign me.
