### ISSUE TITLE
Plant the Grass

### ISSUE THREAD

**Issue by Robaire** [aayushi-droid/Edabit-Solutions#187]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that given an input field (matrix) simulates grass growing from a starting coordinate
**Probelm Link** : https://edabit.com/challenge/szij3YFmix7bMN7En
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Expert

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by shushriya6998** [comment]
I would like to contribute to this in C++. Please assign it to me. Thanks!

**Comment by Robaire** [comment]
@aayushi-droid You can assign this to someone else, I figured I should add some challenges for others to do.
