### ISSUE TITLE
Power Calculator

### ISSUE THREAD

**Issue by jayanthjj** [aayushi-droid/Edabit-Solutions#19]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes voltage and current and returns the calculated power.
**Probelm Link** : https://edabit.com/challenge/a2D3cva6PKrHyqdXC
**Choose one Cateorgy** - Very Easy
**question category** : Math

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
Can I work on this?

**Comment by aayushi-droid** [comment]
- [✓]  Task assigned
@jayanthj737

**Comment by jayanthjj** [comment]
Added circuitPower #64 @aayushi-droid
