### ISSUE TITLE
Is the Number Even or Odd?

### ISSUE THREAD

**Issue by gh4abhi** [aayushi-droid/Edabit-Solutions#192]
Before jumping into Pr first comment for assign.

**Problem statement** : Is the Number Even or Odd?
**Probelm Link** :  https://edabit.com/challenge/65dsmYkHsenAJ3979
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Very Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program tells whether the entered number is odd or even.
 * Problem Link : https://edabit.com/challenge/65dsmYkHsenAJ3979
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by wimanshaherath** [comment]
Can you assign me to this issue?

**Comment by khushi-gupta** [comment]
Hi, Kindly assign this issue to me. Thankyou.
