### ISSUE TITLE
Quadratic Equation in Cpp 

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#2]
Before jumping into Pr first comment for assign.

**Problem statement:**: Create a function to find only the root value of `x` in any quadratic equation `ax^2 + bx + c`. The function will take three arguments.

Link: https://edabit.com/challenge/nasKYub6qEAfQcFuy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py

- [ ]  In file there should be problem statement and link to probelm
    example - 
```cpp
/* this program will add two numbers
    * Problem : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020
Good Luck,

**Comment by alocaputo** [comment]
I'd like to do it

**Comment by subramanian0** [comment]
can i work on this?

**Comment by jayanthjj** [comment]
**If not yet assigned would love to work.**

**Comment by aayushi-droid** [comment]
@alphaxyz assigned, comment priority.
I hope you read all the requirements. Make you PR between 1 Oct - 31 Oct for Vaild HacktoberFest PR.

@subramanian0 & @jayanthj737 guys please create an new issue using template. 
Find the probelm task on Edabit.

**Comment by SugandhiGupta** [comment]
please assign this to me!
thank you
