### ISSUE TITLE
Convert Minutes into Seconds

### ISSUE THREAD

**Issue by jayanthjj** [aayushi-droid/Edabit-Solutions#20]
Before jumping into Pr first comment for assign.

**Problem statement** : Write a function that takes an integer minutes and converts it to seconds.
**Probelm Link** : https://edabit.com/challenge/MtNAJmJZ49i5Xf3AW
**Choose one Cateorgy** - Very Easy
**question category** : Math

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
Please Assign @aayushi-droid

**Comment by aayushi-droid** [comment]
- [✓]  Task assigned
@jayanthj737

**Comment by Jayshah6699** [comment]
```c++
int main()
{
    int bla;
    cin>>bla;
    bla*=60;
    cout<<bla;
    return 0;
}
```
`Is it the task?`

**Comment by aayushi-droid** [comment]
@Jayshah6699 
no it was sample program to show how `ProblemStatement` and `ProblemLink` will be add in a program.

- you have to clone the repo and find the task and assign yourself.
-  You have to make a PR after creating program

But this task is already assigned.

**Comment by Jayshah6699** [comment]
Will, it counted in hacktober fest?

**Comment by aayushi-droid** [comment]
yes, But you have to make PR between 1 October to 31 October.
@Jayshah6699

**Comment by Jayshah6699** [comment]
Is c++ mandatory or I can write in python?

**Comment by aayushi-droid** [comment]
@jayanthj737  For Python Please Refer this Repository https://github.com/Py-Droid/Python-Thunder/

**Comment by jayanthjj** [comment]
@aayushi-droid Added Convert #62
