### ISSUE TITLE
Find Area Of Triangle

### ISSUE THREAD

**Issue by khushi-gupta** [aayushi-droid/Edabit-Solutions#201]
Before jumping into Pr first comment for assign.

**Problem statement** :Write a function that takes the base and height of a triangle and return its area.
**Probelm Link** : 
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
Category-Very Easy
**question category** : https://edabit.com/challenge/3CaszbdZYGN4otQD8

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by khushi-gupta** [comment]
Kindly assign this issue to me. Thanks

**Comment by shreyraj2002** [comment]
Please assign this issue to me

**Comment by Hitesh18082001** [comment]
Please assign  me this issue. I want to fix it.

**Comment by kamalmulani** [comment]
does this problem require solution in c++ if yes, then please assign this to me.

**Comment by dhavalmaniyar** [comment]
please assign to me.
