### ISSUE TITLE
Reverse String Order

### ISSUE THREAD

**Issue by mrigankdembla** [aayushi-droid/Edabit-Solutions#202]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes a string as its argument and returns the string in reversed order.
**Probelm Link** : https://edabit.com/challenge/gYxDahmv8CbWmiThc
**Choose one Cateorgy** - Easy 
**question category** : Strings

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by mrigankdembla** [comment]
Please assign this issue to me

**Comment by mrigankdembla** [comment]
Please review the PR #203

**Comment by Mayankjha997** [comment]
Please assign this issue to me i will share the algorithm in c language

**Comment by parjanyaacoder** [comment]
I will like to work on this issue in Java and C++. Please assign.
