### ISSUE TITLE
Return the Middle Character(s) of a String

### ISSUE THREAD

**Issue by mrigankdembla** [aayushi-droid/Edabit-Solutions#206]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes a string and returns the middle character(s). If the word's length is odd, return the middle character. If the word's length is even, return the middle two characters.
**Probelm Link** : https://edabit.com/challenge/p3SCSXaWQLWpvqCYZ
**Choose one Cateorgy** - Easy 
**question category** : Strings,Math

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by mrigankdembla** [comment]
Please assign this issue to me, thanks !

**Comment by mrigankdembla** [comment]
Please review the PR #207 , thanks!

**Comment by Hitesh18082001** [comment]
I want to fix this issue. Please assign it to me.
Thanks!!

**Comment by on-error** [comment]
I want to fix this issue. Please assign it to me.
Thanks!!
