### ISSUE TITLE
Count Ones in Binary Representation of Integer

### ISSUE THREAD

**Issue by keshav304** [aayushi-droid/Edabit-Solutions#21]
Before jumping into Pr first comment for assign.

Function that Count the amount of ones in the binary representation of an integer. :
Probelm Link : https://edabit.com/challenge/GbyPdqNnp75Wci7Cn
Choose one Cateorgy - Easy
question category : Numbers

---
Before submitting a PR please Check some details.

- [x]  fileName formet should be in camelcase
example- returnTheNextNumber.py

- [x]  Choose label for Problem , example- "good first issue", "easy"

- [x] In file there should be problem statement and link to problem

```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```
This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
hey @aayushi-droid  please assign

**Comment by aayushi-droid** [comment]
- [✓]  Task assigned
@keshav304

**Comment by aayushi-droid** [comment]
- [x] Task Completed
