### ISSUE TITLE
Hitting the Jackpot 

### ISSUE THREAD

**Issue by Madhur215** [aayushi-droid/Edabit-Solutions#213]
Before jumping into Pr first comment for assign.

**Problem statement**: Create a function that takes in an array (slot machine outcome) and returns true if all elements in the array are identical, and false otherwise. The array will contain 4 elements.
**Probelm Link** : https://edabit.com/challenge/5eStPo3wrZRju7j9G
**Choose one Cateorgy** - Easy
**question category** : C++

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Madhur215** [comment]
Please assign it to me.

**Comment by iFrogHop2Worlds** [comment]
I could do this, assign to me please

**Comment by anshumyname** [comment]
I would also like to work on the problem and can add C++, C and python solutions also.
