### ISSUE TITLE
XOR SWAP

### ISSUE THREAD

**Issue by pranavbharadwaj007** [aayushi-droid/Edabit-Solutions#215]
Before jumping into Pr first comment for assign.

**Problem statement** :This is more informational than a challenge. You can actually switch 2 variables with the XOR operation ^. XOR works with two arguments. It turns both arguments in their binary representation, and for each bit, returns 1 if they are different, 0 otherwise.

The return value is the decimal representation of the new binary string. So, if you don't know how to do it, go play around with it! After some time on paper, you will understand what is going on, and how it works.

Your job is to switch 2 variables using the XOR operator, which means your return statement should be return std::make_pair(a, b), but the variables need to be switched.

**Probelm Link** : <a href="https://edabit.com/challenge/dHYXiEXydZxrwntBq">click here</a>
**Choose one Cateorgy** -  Easy
**question category** : bit_operation,language_fundamentals

---
Before submitting a PR please Check some details.

- [x] fileName format should be in camelcase
    example- return Xorswap.cpp
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/dHYXiEXydZxrwntBq
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by pranavbharadwaj007** [comment]
@aayushi-droid  pls assign this issue to me

**Comment by Hitesh18082001** [comment]
please assign this issue to me.
thanks!!

**Comment by Gautam-Diwan** [comment]
pls assign this issue

**Comment by sethivansh6** [comment]
Assign me this issue or the other ones you like I can code them C++, JAVA, and JS.
