### ISSUE TITLE
Power Calculator

### ISSUE THREAD

**Issue by AviSharmaaa** [aayushi-droid/Edabit-Solutions#218]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes voltage and current and returns the calculated power.
**Probelm Link** :  https://edabit.com/challenge/a2D3cva6PKrHyqdXC
**Choose one Cateorgy** - Very Easy 
**question category** : 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by AviSharmaaa** [comment]
Please assign this to me

**Comment by Manavi18** [comment]
I can implement in python if needed.

**Comment by Nusratillo777** [comment]
Please assign this to me

**Comment by dhavalmaniyar** [comment]
please assign this task to me.

**Comment by princekalra** [comment]
i want to work  on this please assign it to me
