### ISSUE TITLE
Oddly or Evenly Positioned

### ISSUE THREAD

**Issue by keshav304** [aayushi-droid/Edabit-Solutions#22]
Before jumping into Pr first comment for assign.

Function that returns the characters from a list or string r on odd or even positions, depending on the specifier s. :
Probelm Link : https://edabit.com/challenge/KQe5w8AdSLbweW8ck
Choose one Cateorgy - Hard
question category : Numbers, Arrays

---
Before submitting a PR please Check some details.

- [ ]  fileName formet should be in camelcase
example- returnTheNextNumber.py

- [ ]  Choose label for Problem , example- "good first issue", "easy"

- [ ] In file there should be problem statement and link to problem

```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```
This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
Hey @aayushi-droid please assign

**Comment by aayushi-droid** [comment]
- [✓]  Task assigned
@keshav304

**Comment by PoojaPatel21** [comment]
Hey, @keshav304 can I code this in python, and if so can you assign this to me?

**Comment by aayushi-droid** [comment]
Thanks, @PoojaPatel21
For python Check Repo -- https://github.com/Py-Droid/Python-Thunder/ and create issue with details.
