### ISSUE TITLE
LOWEST COMMON DIVISOR

### ISSUE THREAD

**Issue by Hitesh18082001** [aayushi-droid/Edabit-Solutions#223]
Before jumping into Pr first comment for assign.

Problem statement :Write a program to find the lowest common divisor of two numbers.
Probelm Link : https://edabit.com/challenge/BzEQsTSmPATbsZJCR
Choose one Cateorgy -  Medium 
question category: loop,maths 

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Hitesh18082001** [comment]
please assign it to me

**Comment by amul-dhungel** [comment]
Assign this to me

**Comment by rishabh15b** [comment]
Can you please assign this problem to me?

**Comment by Gautam-Diwan** [comment]
pls assign to me @Hitesh18082001

**Comment by chiillax** [comment]
Could you please assign me for this task ?
