### ISSUE TITLE
Check if the String is a Palindrome

### ISSUE THREAD

**Issue by Nusratillo777** [aayushi-droid/Edabit-Solutions#225]
Before jumping into Pr first comment for assign.

**Problem statement** : A palindrome is a word, phrase, number or other sequence of characters which reads the same backward or forward, such as madam or kayak.

Write a function that takes a string and determines whether it's a palindrome or not. The function should return a boolean (true or false value).
**Probelm Link** : https://edabit.com/challenge/FSeXe93hxXFyJQpzN
**Choose one Cateorgy** - Medium
**question category** : strings, validation

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Nusratillo777** [comment]
please assign me

**Comment by Monish-P** [comment]
Hey @Nusratillo777 . Could you please assign me this?

**Comment by vineetsharma36** [comment]
Hey can you assign me this problem?

**Comment by shashwat9kumar** [comment]
Hey!!
Could I be assigned a problem too???

**Comment by rajinderpalsingh2001** [comment]
Can you please assign this problem to me, I will surely meet the program requirements.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by vidit624** [comment]
I'll be glad to work on this

**Comment by chiillax** [comment]
Could you please assign me for this task ?
