### ISSUE TITLE
Minimum Removals to Make Two Strings Anagrams

### ISSUE THREAD

**Issue by ghost** [aayushi-droid/Edabit-Solutions#226]
Before jumping into Pr first comment for assign.

Problem statement-Minimum Removals to Make Two Strings Anagrams
Problem Link-https://edabit.com/challenge/NBi75bkHrhTTxmxST
Category-Hard
question category-strings

**Problem statement** :
**Probelm Link** : 
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
please assign this problem to me, this is my first pull request and hacktoberfest participation

**Comment by SugandhiGupta** [comment]
please assign this to me!
thank you

**Comment by chiillax** [comment]
Could you please assign me for this task ?
