### ISSUE TITLE
Mini Peaks

### ISSUE THREAD

**Issue by ghost** [aayushi-droid/Edabit-Solutions#227]
Before jumping into Pr first comment for assign.

Problem statement:Write a function that returns all the elements in an array that are strictly greater than their adjacent left and right neighbors.
Problem Link-https://edabit.com/challenge/5KAsvzdc9DLfEx65t
Category-Hard
Question category-Arrays

**Problem statement** :
**Probelm Link** : 
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
can i start working on this?

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by SugandhiGupta** [comment]
please assign this to me!
thank you
