### ISSUE TITLE
Tally Marks

### ISSUE THREAD

**Issue by ashishrrs** [aayushi-droid/Edabit-Solutions#228]
Before jumping into Pr first comment for assign.

**Problem statement** :Create a function that can convert from normal notation to tally-mark notation and vice versa. In tally-mark notation, a number can be decomposed as the sum of 5s + remainder.

The function will look like this: switchNotation([current scores], desired notation)

**Probelm Link** : https://edabit.com/challenge/deeB7yAgunvLKf4fJ
**Choose one Cateorgy** -  Hard
**question category** : arrays,strings

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by mrinal07** [comment]
I want to contribute please assign it to me.

**Comment by khushi2912** [comment]
I would like to work on this issue. Can you assign this to me?
