### ISSUE TITLE
Burrrrrrp

### ISSUE THREAD

**Issue by ghost** [aayushi-droid/Edabit-Solutions#229]
Before jumping into Pr first comment for assign.
Problem statement-Create a function that returns the string "Burp" with the amount of "r's" determined by the input parameters of the function.
problem link-https://edabit.com/challenge/vxpP4nnDhRr2Yc3Lo
category-easy
question category-strings

**Problem statement** :
**Probelm Link** : 
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by YourGoodFriendSP** [comment]
please assign this to me

**Comment by SugandhiGupta** [comment]
please assign this to me!
thank you

**Comment by ajay272191** [comment]
Hi  @YourGoodFriendSP  Plese assign this Problem to me. Thank you.

**Comment by shivangigoel1302** [comment]
Can you assign this to me? I would like to do it in c++
