### ISSUE TITLE
Words With Duplicate Letters

### ISSUE THREAD

**Issue by keshav304** [aayushi-droid/Edabit-Solutions#23]
Before jumping into Pr first comment for assign.

Problem statement : Given a common phrase, return False if any individual word in the phrase contains duplicate letters. Return True otherwise.
Probelm Link : https://edabit.com/challenge/WS6hR6b9EZzuDTD26
Choose one Cateorgy - Hard
question category : Strings

---
Before submitting a PR please Check some details.

- [ ]  fileName formet should be in camelcase
example- returnTheNextNumber.py

- [ ]  Choose label for Problem , example- "good first issue", "easy"

- [ ] In file there should be problem statement and link to problem

```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```
This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
Hey @aayushi-droid please assign

**Comment by aayushi-droid** [comment]
- [x] task assigned

**Comment by PoojaPatel21** [comment]
@keshav304  Can I code this in python?

**Comment by aayushi-droid** [comment]
Thanks, @PoojaPatel21
For python Check Repo --  https://github.com/Py-Droid/Python-Thunder/ and create issue with details.
