### ISSUE TITLE
Perfect Square Patch

### ISSUE THREAD

**Issue by chiru-cd** [aayushi-droid/Edabit-Solutions#231]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes an integer and outputs an n x n square solely consisting of the integer n.
**Probelm Link** : https://edabit.com/challenge/omTRzwvBibk4etBkx
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Medium

---
Before submitting a PR please Check some details.

- [X] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [X]  Choose label for Problem , example- "good first issue", "easy"
- [X]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by chiru-cd** [comment]
I would like to work on this. Please assign.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.
