### ISSUE TITLE
Array Of Multiples

### ISSUE THREAD

**Issue by khushi-gupta** [aayushi-droid/Edabit-Solutions#234]
Before jumping into Pr first comment for assign.

**Problem statement** :Create a function that takes two numbers as arguments (num, length) and returns an array of multiples of num until the array length reaches length.
**Problem Link** : https://edabit.com/challenge/7oyHeyJR2LkB3hr8g
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Medium

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by khushi-gupta** [comment]
Hi, Kindly assign this issue to me. Thanks

**Comment by kalrasagar** [comment]
Hey, kindly assign this issue to me.

**Comment by khushi-gupta** [comment]
I have completed this task. Kindly check.
