### ISSUE TITLE
Next Largest Number

### ISSUE THREAD

**Issue by div5252** [aayushi-droid/Edabit-Solutions#236]
Before jumping into Pr first comment for assign.

**Problem statement** : Write a function that returns the next largest number that can be created from the same digits as the input.
**Probelm Link** : https://edabit.com/challenge/WtfjhA6dydKSERz6G
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very hard

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by sakshi0461** [comment]
Please assign this to me

**Comment by Deepak290701** [comment]
Hello , Can you please assign this task to me .

**Comment by ajay272191** [comment]
Hi, Can you please assign this to me. Thank you.
