### ISSUE TITLE
Would love to take up this problem.

### ISSUE THREAD

**Issue by tharun571** [aayushi-droid/Edabit-Solutions#237]
Before jumping into Pr first comment for assign.

**Problem statement** :
**Probelm Link** : 
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Deepak290701** [comment]
Hello ,can you please give the problem name and assign it to me.

**Comment by khushi2912** [comment]
I would love to work on this. Can you assign this to me?

**Comment by aayushi-droid** [comment]
No problem statement and problem link.
