### ISSUE TITLE
Filter Primes from a List

### ISSUE THREAD

**Issue by keshav304** [aayushi-droid/Edabit-Solutions#24]
Before jumping into Pr first comment for assign.

Problem statement : Write a function that takes a list and returns a new list containing only prime numbers.
Probelm Link : https://edabit.com/challenge/yXZhG7zq6dWhWhirt
Choose one Cateorgy - Hard
question category : Numbers

---
Before submitting a PR please Check some details.

- [ ]  fileName formet should be in camelcase
example- returnTheNextNumber.py

- [ ]  Choose label for Problem , example- "good first issue", "easy"

- [ ] In file there should be problem statement and link to problem

```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```
This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
Hey @aayushi-droid please assign

**Comment by aayushi-droid** [comment]
please Don't modify the template. you removed checkbox by mistake

**Comment by aayushi-droid** [comment]
- [x] Task Assigned

**Comment by Jayshah6699** [comment]
Hey @aayushi-droid kindly assign

**Comment by aayushi-droid** [comment]
@Jayshah6699 Task is already assigned. I will add more program tomorrow. So  I will you assign there.

Keep an eye out.
