### ISSUE TITLE
Return the Sum of Two Numbers

### ISSUE THREAD

**Issue by pranavgoel29** [aayushi-droid/Edabit-Solutions#240]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes two numbers as arguments and return their sum.
**Probelm Link** : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by sakshi0461** [comment]
Please assign this to me

**Comment by pranavgoel29** [comment]
I would like to work on this @aayushi-droid please assign it to me.

**Comment by DS-73** [comment]
Hello,
Please assign this task to me I can solve it

Thank you

**Comment by pranavgoel29** [comment]
@aayushi-droid please assign this to me.

**Comment by anantbharti30** [comment]
Please assign to me

**Comment by pranavgoel29** [comment]
@anantbharti30 you have to open an new issue with you problem task like I did so it can be assigned to you

**Comment by aayushi-droid** [comment]
Thanks for messaging but priority will give to issue-author(who created the issue)
