### ISSUE TITLE
Derivative of a Function

### ISSUE THREAD

**Issue by Nusratillo777** [aayushi-droid/Edabit-Solutions#242]
Before jumping into Pr first comment for assign.

**Problem statement** : Directions: Create a function that takes numbers b and m as arguments and returns the derivative of the function f(x)=x^b with respect to x at the point where x=m, where band m are constants.
**Probelm Link** : https://edabit.com/challenge/sR3aNNQ9kJoSurDLK
**Choose one Cateorgy** - Medium
**question category** : math, numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- derivative.cpp
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Nusratillo777** [comment]
please assign me

**Comment by kubercodes** [comment]
Please assign this to me

**Comment by danglingP0inter** [comment]
please assign this to me

**Comment by Hackerbone** [comment]
please assign me this ! thanks!

**Comment by Nusratillo777** [comment]
Why you assigned another person? I created this issue and solved it. But I'm waiting to create PR?

**Comment by Nusratillo777** [comment]
Because you wrote did make PR before assigning.
