### ISSUE TITLE
Reverse Letters, Keep Numbers in Place

### ISSUE THREAD

**Issue by Nusratillo777** [aayushi-droid/Edabit-Solutions#243]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that reverses letters in a string but keeps digits in their current order.
**Probelm Link** : https://edabit.com/challenge/7MB4iAGx53BMgHAC6
**Choose one Cateorgy** - Hard
**question category** : logic, strings

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- reverse.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Nusratillo777** [comment]
Please assign me

**Comment by Gautam-Diwan** [comment]
assign to me

**Comment by luccanunes** [comment]
hey there! i would really like to be assigned to this

**Comment by SugandhiGupta** [comment]
please assign this to me!
thank you
