### ISSUE TITLE
Reverse Coding Challenge #5

### ISSUE THREAD

**Issue by Nusratillo777** [aayushi-droid/Edabit-Solutions#244]
Before jumping into Pr first comment for assign.

**Problem statement** : This is a reverse coding challenge. Normally you're given explicit directions with how to create a function. Here, you must generate your own function to satisfy the relationship between the inputs and outputs.

Your task is to create a function that, when fed the inputs below, produce the sample outputs shown.
**Probelm Link** : https://edabit.com/challenge/64CeZWx5wWhTxhHLL
**Choose one Cateorgy** - Hard
**question category** : logic, math, numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Nusratillo777** [comment]
Please assign me

**Comment by danglingP0inter** [comment]
please assign this to me
