### ISSUE TITLE
Matrix Transpose

### ISSUE THREAD

**Issue by ashishrrs** [aayushi-droid/Edabit-Solutions#251]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that transposes a 2D matrix.
**Probelm Link** : https://edabit.com/challenge/4KaoDvxaFSmf38bPQ
**Choose one Cateorgy** -Hard
**question category** : arrays, math

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by indranil-tiwary** [comment]
Hey @ashishrrs, Please assign this to me!

**Comment by Gautam-Diwan** [comment]
I will do it. Assign me this

**Comment by avsd47** [comment]
hey @ashishrrs pls assign me to this

**Comment by prajwalscodestack** [comment]
Hey there please assign me this to me
