### ISSUE TITLE
Are the Numbers Equal?

### ISSUE THREAD

**Issue by gh4abhi** [aayushi-droid/Edabit-Solutions#252]
Before jumping into Pr first comment for assign.

**Problem statement** : Are the Numbers Equal?
**Probelm Link** :  https://edabit.com/challenge/uSiEPX7YrhNsqtzMr
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Very Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will check whether the numbers are equal or not ?
 * Problem Link : https://edabit.com/challenge/uSiEPX7YrhNsqtzMr
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by anantbharti30** [comment]
please approve

**Comment by anantbharti30** [comment]
please approve

**Comment by rgarg-2711** [comment]
i want to work on this issue. can u assign it to me plz.

**Comment by Zaidtech** [comment]
@gh4abhi , can i work on this issue?
