### ISSUE TITLE
Using the :? Operator

### ISSUE THREAD

**Issue by gh4abhi** [aayushi-droid/Edabit-Solutions#254]
Before jumping into Pr first comment for assign.

**Problem statement** : Using the :? Operator
**Probelm Link** :  https://edabit.com/challenge/Qs9aWacyy5jXdNz45
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : Using the :? Operator
 * Problem Link : https://edabit.com/challenge/Qs9aWacyy5jXdNz45
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by rajarshisg** [comment]
Hey, please assign it to me.

**Comment by khushi2912** [comment]
I would like to work on this, can you assign this to me?

**Comment by asad2200** [comment]
Hey @gh4abhi. This is my first hecktoberfest contribution. I would like to work on this please assign it to me.

**Comment by anantbharti30** [comment]
Please assign to me

**Comment by gh4abhi** [comment]
I am not the owner of this repo so I cannot assign this to anyone.
