### ISSUE TITLE
Jump Game - II

### ISSUE THREAD

**Issue by byte-coding** [aayushi-droid/Edabit-Solutions#255]
**Problem Link:** https://leetcode.com/problems/jump-game-ii/

Given an array of non-negative integers, you are initially positioned at the first index of the array.
Each element in the array represents your maximum jump length at that position.
Your goal is to reach the last index in the minimum number of jumps.

**Example:**
Input: [2,3,1,1,4]
Output: 2
**Explanation:** The minimum number of jumps to reach the last index is 2.
    Jump 1 step from index 0 to 1, then 3 steps to the last index.
Note:
You can assume that you can always reach the last index.

**Problem Type:** Hard

**Comment by Gautam-Diwan** [comment]
assign this to me @byte-coding

**Comment by byte-coding** [comment]
@aayushi-droid Can you please assign this issue to me? 
 I am working on it.

**Comment by prajwlr** [comment]
Hi. I would love to contribute. Please assign it to me.

**Comment by chiillax** [comment]
Could you please assign me for this task ?
