### ISSUE TITLE
Multiple of 100

### ISSUE THREAD

**Issue by gh4abhi** [aayushi-droid/Edabit-Solutions#267]
Before jumping into Pr first comment for assign.

**Problem statement** : Multiple of 100
**Probelm Link** : https://edabit.com/challenge/b3tArYGfMfmq78MoS
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will check whether the number is divisible by 100 or not.
 * Problem Link : https://edabit.com/challenge/b3tArYGfMfmq78MoS
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by prajwlr** [comment]
Hi. I would love to contribute. Please assign it to me.

**Comment by dinijian** [comment]
Hello @gh4abhi. I want to contribute to this issue. Please assign it to me. I will do it in C++.

**Comment by dinijian** [comment]
Hello. I want to contribute to this issue. Please assign it to me. I will do it in C++.

**Comment by NidhiNivedita6** [comment]
Please assign this to me. I will do it in C.

**Comment by Mayankjha997** [comment]
Please assign this to me. I will do it in Python.

**Comment by Awanit512** [comment]
please assign this work to me.

**Comment by garvitsharma05** [comment]
I would like to contribute.
