### ISSUE TITLE
Pi to N Decimal Places

### ISSUE THREAD

**Issue by ThePsyk3y** [aayushi-droid/Edabit-Solutions#27]
Before jumping into Pr first comment for assign.

**Problem statement** : Given a number n, write a function that returns PI to n decimal places.
**Probelm Link** : https://edabit.com/challenge/wzPBMkanx2Db8Kpmp
**Choose one Cateorgy** - Medium
**question category** : numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ThePsyk3y** [comment]
@aayushi-droid, can you assign this to me?

**Comment by aayushi-droid** [comment]
- [x]  Task assigned
Go Ahead
@ThePsyk3y
