### ISSUE TITLE
Using ?:

### ISSUE THREAD

**Issue by gh4abhi** [aayushi-droid/Edabit-Solutions#270]
Before jumping into Pr first comment for assign.

**Problem statement** : Char-to-ASCII
**Probelm Link** : https://edabit.com/challenge/TdcPGgdJda6XGJian
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program finds the ASCII value of a character.
 * Problem Link : https://edabit.com/challenge/TdcPGgdJda6XGJian
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by rodrigoboos** [comment]
hello, please assign it to me

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Awanit512** [comment]
hi can you please assign this to me.
