### ISSUE TITLE
Char-to-ASCII

### ISSUE THREAD

**Issue by gh4abhi** [aayushi-droid/Edabit-Solutions#271]
Before jumping into Pr first comment for assign.

**Problem statement** : Char-to-ASCII
**Probelm Link** :   https://edabit.com/challenge/TdcPGgdJda6XGJian
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will find the ASCII value of character.
 * Problem Link :  https://edabit.com/challenge/TdcPGgdJda6XGJian
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Awanit512** [comment]
Please can you assign this to me.

**Comment by gauriguglani11** [comment]
Hey, hope you are doing good. Kindly assign this to me. Thank you!

**Comment by arvind0009** [comment]
please assign this to me..
