### ISSUE TITLE
Reverse a string recursively

### ISSUE THREAD

**Issue by Rituraj-commits** [aayushi-droid/Edabit-Solutions#272]
Before jumping into Pr first comment for assign.

**Problem statement** : This program will reverse a string recursively.
**Probelm Link** : https://edabit.com/challenge/HXGx9oXukEgsFK6PH
**Choose one Cateorgy** - Medium
**question category** : recursion,strings 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : Write a function that reverses a string. Make your function recursive.
 * Problem Link : https://edabit.com/challenge/HXGx9oXukEgsFK6PH
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Rituraj-commits** [comment]
Please @aayushi-droid assign this to me

**Comment by GTron-1729** [comment]
Hey @Rituraj-commit. I would be glad to do this 👍.

**Comment by gauriguglani11** [comment]
Can you please Assign this to me, it would be a pleasure working on this!

**Comment by vaishnavijha** [comment]
Can u assign this to me?

**Comment by JoshuaOloton** [comment]
Can u assign this to me?
