### ISSUE TITLE
ArrayOfTables

### ISSUE THREAD

**Issue by Hitesh18082001** [aayushi-droid/Edabit-Solutions#274]
Before jumping into Pr first comment for assign.

Problem statement :Write a function which takes two a arguments (num,length) and return a array of multiple of num and size of 
                                 array is length. For eg:-(5,4) return (5,10,15,20) , (12,6) return (12,24,36,48,60,72).
Probelm Link: https://edabit.com/challenge/ebcd4Xu8TLizaj6dm
Choose one Cateorgy - Medium 
**question category** : math,array.

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Hitesh18082001** [comment]
Please assign it to me.
Thanks!!

**Comment by srai0109** [comment]
please assign it to me.

**Comment by TanmayBhosale** [comment]
please assign it to me
thank you

**Comment by anuragdevon** [comment]
Please assign it to me
Thanks!

**Comment by Hackerbone** [comment]
Please assign me this thanks!
