### ISSUE TITLE
Recursion: Fibonacci Numbers

### ISSUE THREAD

**Issue by reginaEmyk** [aayushi-droid/Edabit-Solutions#275]
Before jumping into Pr first comment for assign.

**Problem statement** : The nth Fibonacci number
**Probelm Link** : https://edabit.com/challenge/BfWjk87JLY5roKzg6
**Choose one Cateorgy** - Easy
**question category** : math, recursion

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will recursively calculate the nth given number in Fibonacci's sequence
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by reginaEmyk** [comment]
Hello, I'm a newbie c++ programmer, please assign this to me

**Comment by AnshMishra2001** [comment]
pls assign this to me.

**Comment by AnshMishra2001** [comment]
I can code it in Java, C++ and Python

**Comment by Dhi13man** [comment]
Do assign. I can do it in any language. Easy category.

**Comment by ayu16** [comment]
please can you assign this to me I can do it any language

**Comment by Mayankjha997** [comment]
please assign me i will do in c language

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by sethivansh6** [comment]
Assign me any problem in CPP or Java I am ready to work on it.

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by rgarg-2711** [comment]
can u assign this issue to me plz.

**Comment by ghost** [comment]
Please assign this to me.

**Comment by Zaidtech** [comment]
@BananaMoshpit  can i work on this issue!!

**Comment by reginaEmyk** [comment]
@Zaidtech it's not me who owns the rep, I think you'd be assigned after submitting a pull request linked to an issue that you (may) open.

But there's already a fibonacci function added so there's no use adding another
