### ISSUE TITLE
How Many Vowels?

### ISSUE THREAD

**Issue by pranavgoel29** [aayushi-droid/Edabit-Solutions#278]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes a string and returns the number (count) of vowels contained within it.
**Probelm Link** :  https://edabit.com/challenge/jwPaBe2xjE46baPoG
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Easy

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by pranavgoel29** [comment]
@aayushi-droid please Assign this to me.

**Comment by Awanit512** [comment]
please assign this to me.I love to work on it.

**Comment by aktgb31** [comment]
Please assign this to me

**Comment by satwik16** [comment]
I would love to work on it ,please assign this to me

**Comment by Procoder16** [comment]
@pranavgoel29 sir, I would like to work on this issue.

Can you please assign me this issue.

**Comment by Gautam-Diwan** [comment]
please assign me this @pranavgoel29

**Comment by pranavgoel29** [comment]
@Gautam-Diwan @Procoder16 @satwik16 @aktgb31 @Awanit512 
I am not allowed to assign it to anyone as you have to choose an question and make an issue about it so it can be assigned to you they are assigning it to those who post the issue. So respectively choose a different problem and make an issue about it.

**Comment by pranavgoel29** [comment]
@aayushi-droid Please assign it to me.
