### ISSUE TITLE
Rainwater trapping problem

### ISSUE THREAD

**Issue by vaishnavijha** [aayushi-droid/Edabit-Solutions#296]
Before jumping into Pr first comment for assign.

**Problem statement** :Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining.
**Probelm Link** : https://practice.geeksforgeeks.org/problems/trapping-rain-water/0
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Medium

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vaishnavijha** [comment]
Please assign it to me

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by rgarg-2711** [comment]
can u plzz assign this issue to me.
