### ISSUE TITLE
Recursion: Reverse a String in Cpp

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#3]
Before jumping into Pr first comment for assign.

**Problem statement:**: Write a function that reverses a string. Make your function recursive.
Link: https://edabit.com/challenge/HXGx9oXukEgsFK6PH

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py

- [ ]  In file there should be problem statement and link to probelm
- [ ]  Add label for Problem
    example - 
```cpp
/* this program will add two numbers
    * Problem : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by subramanian0** [comment]
Can I work on this as part of hacktoberfest?

**Comment by DaniAcu** [comment]
Could I pick this?

**Comment by DaniAcu** [comment]
Could I pick this?

**Comment by aayushi-droid** [comment]
@subramanian0 assigned based on priority comment.

@DaniAcu you can make a new issue for new proble. Find problem from Edabit.com

**Comment by subramanian0** [comment]
@aayushi-droid  : I was assigned this but the code was already added to the repo.
