### ISSUE TITLE
Quadratic Equation root

### ISSUE THREAD

**Issue by Swarn10** [aayushi-droid/Edabit-Solutions#310]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function to find only the root value of x in any quadratic equation `ax^2+bx+c`. The problem will take 3 arguments : 
- `a` as the co-efficient of `x^2`
- `b` as the co-efficient of `x`
- `c` as the constant term

**Problem Link** :  https://edabit.com/challenge/nasKYub6qEAfQcFuy
**Choose one category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**Question category** : Medium

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Swarn10** [comment]
@aayushi-droid Please assign this issue to me.

**Comment by mayankgoyal-13** [comment]
Can I do this using Python?

**Comment by shivangigoel1302** [comment]
Can you assign this to me?
I would like to do this in C++

**Comment by adisrivastava121** [comment]
Can you assign this to me? This is my First attempt for Open source. I want to develop it using c++.

**Comment by divyanayal** [comment]
Please assign me this task.
