### ISSUE TITLE
Maskify the String

### ISSUE THREAD

**Issue by Hackerbone** [aayushi-droid/Edabit-Solutions#313]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes a string, transforms all but the last four characters into "#" and returns the new masked string.

Examples:
_maskify("4556364607935616") ➞ "############5616"_
_maskify("64607935616") ➞ "#######5616"_
_maskify("1") ➞ "1"_
_maskify("") ➞ ""_

**Probelm Link** :  https://edabit.com/challenge/2MAr9P4TTGooXS8Xa
**Choose one Cateorgy** - Easy
**question category** : String manipulation

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Hackerbone** [comment]
Please assign me this task. @aayushi-droid

**Comment by shivangigoel1302** [comment]
Can you assign this to me? I would like to do it in C++

**Comment by Hackerbone** [comment]
@aayushi-droid sent a PR , pls merge
