### ISSUE TITLE
Here, I have made some corrections in spelling mistakes.

### ISSUE THREAD

**Issue by adisrivastava121** [aayushi-droid/Edabit-Solutions#317]
Before jumping into Pr first comment for assign.

**Problem statement** :
**Problem Link** : 
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [x] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is valid for HacktoberFest,2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck.

**Comment by Mrsterius** [comment]
Please assign this issue to me. This would be my first issue.
I will solve it using C++.

**Comment by shubhamnag14** [comment]
assign me this PR..i will solve it using c+++
