### ISSUE TITLE
Sort by String Length

### ISSUE THREAD

**Issue by keshav304** [aayushi-droid/Edabit-Solutions#32]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that returns an array of strings sorted by length in ascending order.
**Probelm Link** : https://edabit.com/challenge/LDNzJS27GY7aWNcBv
**Choose one Cateorgy** - Medium
**question category** : Strings

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
hey @aayushi-droid please assign

**Comment by aayushi-droid** [comment]
Your Issue format is wrong, you deleted the task button by mistakes.
create an issue, Choose template and fill details, You don't need to write whole template again,

**Comment by aayushi-droid** [comment]
- [x] Task Assigned

**Comment by aayushi-droid** [comment]
#56
