### ISSUE TITLE
Bitwise Operations

### ISSUE THREAD

**Issue by Aakansha99** [aayushi-droid/Edabit-Solutions#320]
Before jumping into Pr first comment for assign.

**Problem statement** :Bitwise Operations
**Probelm Link** : https://edabit.com/challenge/vvuAkYEAArrZvmp6X
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by MayankAg20** [comment]
Could you please assign this issue to me? I am willing to do this task.

**Comment by shubhamnag14** [comment]
could please assign this issue to me.

**Comment by rgarg-2711** [comment]
i want to work on this issue. can u assign it to me.

**Comment by kirti-k** [comment]
please assign me this issue.
