### ISSUE TITLE
Sliding Sum

### ISSUE THREAD

**Issue by Nusratillo777** [aayushi-droid/Edabit-Solutions#328]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that returns the subarrays of n consecutive elements from the original element that sum up to k. The function will have the following form: slidingSum(arr, n, k)
**Probelm Link** : https://edabit.com/challenge/SkJoSKw9i3GQf62k5
**Choose one Cateorgy** - Hard
**question category** : arrays, language fundamentals

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Nusratillo777** [comment]
please assign me

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by rahulmishra11** [comment]
Please assign this task to me.

**Comment by AshwinKul28** [comment]
Hello, could you please assign this task to me?

**Comment by ghost** [comment]
I would love to complete this task. Please assign this to me. 
Thanks!

**Comment by kriti45** [comment]
Hey! I would love to work on this issue, can you please assign this to me?
Thanks!
