### ISSUE TITLE
convert age to days

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#334]
Before jumping into Pr first comment for assign.

**Problem statement** : convert age to days
**Probelm Link** : https://edabit.com/challenge/bL7hSc6Zh4zZJzGmw
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by aayushi-droid** [comment]
@rgarg-2711 issue assigned

**Comment by rgarg-2711** [comment]
thank you @aayushi-droid for assign me this.

**Comment by psymbio** [comment]
function calcAge(age) {
	return age * 365;
}

One line of code is an issue?

**Comment by aayushi-droid** [comment]
Great things are not done by impulse, but by a series of small things brought together. 
@psymbio 
It's a repo for encourage new developers to contribute to open-source. Issue is small or big. Doesn't matter.
