### ISSUE TITLE
Catalan Number Series/ Number of unique bst 

### ISSUE THREAD

**Issue by Jainchhavi16** [aayushi-droid/Edabit-Solutions#344]
Before jumping into Pr first comment for assign.

**Problem statement** :Catalan series is less known by name but this number series is used to solve many important questions like ,Given n, how many structurally unique BST's (binary search trees) that store values 1 to n?
**Probelm Link** : https://leetcode.com/problems/unique-binary-search-trees/
**Choose one Cateorgy** - Medium

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Jainchhavi16** [comment]
I would like to work on this issue I have created .  Its a good question.
Please assign it to me. 
Thanks in advance

**Comment by Jainchhavi16** [comment]
I have created a PR too. Please look into it.
Thanks

**Comment by ankitsri1998** [comment]
Sir please Assign this to me , i can resolve it.
thank you

**Comment by Jainchhavi16** [comment]
@ankitsri1998 I have already created a pr, I request you to find other.

**Comment by ByteCode-Test** [comment]
plz tell me that can i raise an issue and solve it myself  is it possible as u did it ??
