### ISSUE TITLE
Slice of Pie

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#35]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that determines whether or not it's possible to split a pie fairly given these three parameters:

- Total number of slices.
- Number of recipients.
- How many slices each person gets.

**Probelm Link** : https://edabit.com/challenge/zzv5CPD26cfv4pEQX
**Choose one Cateorgy** - Very Easy
**question category** : Algebra, Math, Validation

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
I can work on this! Please Assign. @aayushi-droid

**Comment by aayushi-droid** [comment]
- [x] Assiging task to @jayanthj737

**Comment by jayanthjj** [comment]
@aayushi-droid Added equalSlices.cpp #65

**Comment by sravyasri2001** [comment]
Assign it to me
