### ISSUE TITLE
Name Greeting!

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#36]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes a name and returns a greeting in the form of a string.
**Probelm Link** : https://edabit.com/challenge/MtG39AgXhyeePSiY2
**Choose one Cateorgy** - Very Easy
**question category** : formatting, string

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
Please assign @aayushi-droid

**Comment by aayushi-droid** [comment]
- [x] Assigning Task to @jayanthj737

**Comment by jayanthjj** [comment]
It's done yeah? @aayushi-droid Close?

**Comment by aayushi-droid** [comment]
- [x]  Task Complete
