### ISSUE TITLE
Return the Last Element in an Array

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#37]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that accepts an array of numbers and returns the last number in the array.
**Probelm Link** : https://edabit.com/challenge/4GZcWTiv2GPA9NfcP
**Choose one Cateorgy** - Very Easy
**question category** : Array

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Yash-g17** [comment]
I'd like to contribute to this

**Comment by aayushi-droid** [comment]
- [x] Assigning Task to @Yash-g17 

Go Ahead, Best of Luck

**Comment by sravyasri2001** [comment]
Assign it to me,I can Do.
