### ISSUE TITLE
Roll the Dice

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#38]
Before jumping into Pr first comment for assign.

**Problem statement** : Roll the Dice
**Probelm Link** : https://edabit.com/challenge/6ejJ6e7fLdqzGPa3q
**Choose one Cateorgy** -  Expert 
**question category** : Math, Numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vivekkj123** [comment]
I would like to contribute to this... So please assign me...

**Comment by aayushi-droid** [comment]
- [ ] Task assigning to @vivekkj123 

Best of Luck

**Comment by vivekkj123** [comment]
Sorry, i cant do that now due to some personal issues, so please assign anyone....

**Comment by Robaire** [comment]
Could I get this one?
