### ISSUE TITLE
Find the Odd Integer in Cpp

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#4]
Before jumping into Pr first comment for assign.

**Problem statement:** Create a function that takes an array and finds the integer which appears an odd number of times.
Link: https://edabit.com/challenge/wgnmQTbfssuhvZHqe 

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py

- [x]  In file there should be problem statement and link to probelm
- [x]  Add label for Problem
    example - 
```cpp
/* this program will add two numbers
    * Problem : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by gourav-j** [comment]
I would like to pick it up. Can you assign this to me?

**Comment by aayushi-droid** [comment]
@gourav-j assigned, Take care of all guidelines.
Best of Luck

**Comment by aayushi-droid** [comment]
- [ ✔️] Task Complete
