### ISSUE TITLE
Phone Letter Combination

### ISSUE THREAD

**Issue by Jayshah6699** [aayushi-droid/Edabit-Solutions#41]
Before jumping into Pr first comment for assign.

**Problem statement** :Phone Letter Combination
**Probelm Link** : https://edabit.com/challenge/npLurjMJofmFRCJwx
**Choose one Cateorgy** -  Expert 
**question category** : Algorithms, Arrays, logic, Loops

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. 
 * Problem Link : https://edabit.com/challenge/npLurjMJofmFRCJwx
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Jayshah6699** [comment]
@aayushi-droid Assign the task to me.

**Comment by aayushi-droid** [comment]
- [x] Assigning Task to @Jayshah6699

**Comment by Manoj13-coder** [comment]
assign this task to me actually this question can be solved using backtracking.

**Comment by aayushi-droid** [comment]
@Manoj13-coder 
Create a new file with phoneLetterCombination-alternative.cpp in respective folder, Make sure to not touch previous files created by @Jayshah6699 

- [x]  Task assigning to @Manoj13-coder for Alternative approch.

Note- Make sure to even origin branch with `upstream master` branch

**Comment by Manoj13-coder** [comment]
ok thank you
