### ISSUE TITLE
Area of triangle

### ISSUE THREAD

**Issue by dolonmandal** [aayushi-droid/Edabit-Solutions#46]
Before jumping into Pr first comment for assign.

**Problem statement** :Area of Triangle
**Probelm Link** : https://edabit.com/challenge/HvYiBXgfPtnDHitym
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by dolonmandal** [comment]
I am participating first time in hacktoberfest. Hence created a new issue. Now should I wait for its assignment?

**Comment by aniruddha-5** [comment]
I would like to work on this issue. I am participating for the first time in hacktoberfest.

**Comment by kratikaatgithub** [comment]
Hi @dolonmandal  can you also assign this issue to me? I would like to work on this as part of hacktoberfest 2020.
Thanks

**Comment by vivekkj123** [comment]
Assign this problem to me... I will do my best...

**Comment by Avn007** [comment]
Hi @dolonmandal  , I am taking part for the first time in Hacktoberfest and would very much like to work on this issue.

**Comment by aayushi-droid** [comment]
- [x] Assigning issue to @dolonmandal 

Assigning issue based on comment priority.
Please guys make an issue from https://edabit.com or wait for new issues to come.

**Comment by aniruddha-5** [comment]
Hey, @aayushi-droid I have already made a pull request, will that be counted?

**Comment by aayushi-droid** [comment]
@aniruddha-5 , Pull Request between 1 October -31 October will count.

**Comment by aniruddha-5** [comment]
Okay. @aayushi-droid Can I generally resolve issues in this repo before that? If anyway I can be of any help please let me know!

**Comment by aayushi-droid** [comment]
@aniruddha-5 , Yes sure but make an issue and assigned before making any changes. You can join as maintainer for manage issue and Pull request.

**Comment by ViivekUV** [comment]
Please assign this issue to me. I'd like to work on this.
