### ISSUE TITLE
The Farm Problem

### ISSUE THREAD

**Issue by Avn007** [aayushi-droid/Edabit-Solutions#48]
Before jumping into Pr first comment for assign.

**Problem statement** : In this challenge, a farmer is asking you to tell him how many legs can be counted among all his animals. The farmer breeds three species:
chickens = 2 legs
cows = 4 legs
pigs = 4 legs
The farmer has counted his animals and he gives you a subtotal for each species. You have to implement a function that returns the total number of legs of all the animals.

**Probelm Link** : https://edabit.com/challenge/aADAoRtkbZWEKw9Ap
**Choose one Cateorgy** - Very Easy
**question category** : algorithms, math

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Avn007** [comment]
@aayushi-droid  Hi, can I work on this issue for Hacktoberfest?

**Comment by aayushi-droid** [comment]
Yes sure,

- [x] Issue assigned to @Avn007

**Comment by aayushi-droid** [comment]
#52
