### ISSUE TITLE
Water Jug Problem

### ISSUE THREAD

**Issue by Jayshah6699** [aayushi-droid/Edabit-Solutions#49]
Before jumping into Pr first comment for assign.

**Problem statement** : Given a set of 3 jugs of water that have capacities of a, b, and c liters, find the minimum number of operations performed before each jug has x, y, and z liters. Only jug C will start completely filled.

An operation is any of the following: A jug is emptied, a jug is filled, or water is poured from one jug to another until one of the jugs is either empty or full.

For example, jugs A, B, and C with capacities of 3, 5, and 8, where jugs A and B start empty and C has the full 8, require 2 operations to reach the state of 0, 3, and 5 liters in the jugs.

Create a function that, given an array of jug capacities [A, B, C] and an goal state array [x, y, z], returns the minimum number of operations needed to reach the goal state. If the inputs are invalid or there is no solution, return "No solution."
**Probelm Link** : https://edabit.com/challenge/BMujCYCkTowit85Wq
**Choose one Cateorgy** - Expert 
**question category** : Algoritms, Conditions, Data_structures, Loops

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will solve Water Jug Problem
 * Problem Link : https://edabit.com/challenge/BMujCYCkTowit85Wq
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Jayshah6699** [comment]
@aayushi-droid Kindly assign me the task

**Comment by Mostafa-ashraf19** [comment]
Hello, can I work on this issue for Hacktoberfest?

**Comment by Jayshah6699** [comment]
@Mostafa-ashraf19 Why not? @aayushi-droid assign it to him as soon as possible

**Comment by Jayshah6699** [comment]
@aayushi-droid add an expert label too

**Comment by Mostafa-ashraf19** [comment]
@Jayshah6699 , @aayushi-droid  I solved the problem, what can I do now, make a PR, or setting a solution here in the comments for review!!!

**Comment by ashishrrs** [comment]
I would love to work on it.Please assign me.

**Comment by Jayshah6699** [comment]
> @Jayshah6699 , @aayushi-droid I solved the problem, what can I do now, make a PR, or setting a solution here in the comments for review!!!
@Mostafa-ashraf19 
fork this repo then commit the code in specific folder in given criteria and then you will see pullrequest option there.

**Comment by Mostafa-ashraf19** [comment]
@Jayshah6699, can you tell me your feedback please.

**Comment by aayushi-droid** [comment]
#97 issue merged
