### ISSUE TITLE
Letters Shared Between Two Words

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#5]
Before jumping into Pr first comment for assign.

**Problem statement:** Create a function that returns the number of characters shared between two words.
**Probelm Link:** https://edabit.com/challenge/qeCS48GXtK9NJLc9C
```
sharedLetters("apple", "meaty") ➞ 2
// Since "ea" is shared between "apple" and "meaty".

sharedLetters("fan", "forsook") ➞ 1

sharedLetters("spout", "shout") ➞ 4
```
---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by harisfi** [comment]
I would like to work on this issue.

**Comment by aayushi-droid** [comment]
- [✔️] Task Assigned
@harisfi

**Comment by aayushi-droid** [comment]
- [ ✔️] Task Complete
