### ISSUE TITLE
Hex to Binary

### ISSUE THREAD

**Issue by vivekkj123** [aayushi-droid/Edabit-Solutions#50]
Before jumping into Pr first comment for assign.

**Problem statement** :
Create a function that will take a HEX number and returns the binary equivalent (as a string).
Examples

toBinary(0xFF) ➞ "11111111"

toBinary(0xAA) ➞ "10101010"

toBinary(0xFA) ➞ "11111010"

Notes

The number will be always an 8-bit number.
**Problem Link** : https://edabit.com/challenge/NX5uRSLwuXwsqKfiR
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Very Hard

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vivekkj123** [comment]
@aayushi-droid  Please Assign this issue to me... I will do my best to this.. :),

Thanks,
VIVEK K J,
www.vivekkj.me

**Comment by ashishrrs** [comment]
I would love to work on this.
