### ISSUE TITLE
Find the Smallest and Biggest Numbers

### ISSUE THREAD

**Issue by jayanthjj** [aayushi-droid/Edabit-Solutions#6]
Before jumping into Pr first comment for assign.

**Problem statement: Create a function that takes an array of numbers and return both the minimum and maximum numbers, in that order.**
**Probelm Link: https://edabit.com/challenge/N5P6d6CipYyDg9w2M** 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by jayanthjj** [comment]
@aayushi-droid can I work on this?

**Comment by aayushi-droid** [comment]
@jayanthj737 ya Go ahead.

Best of Luck

**Comment by jayanthjj** [comment]
@aayushi-droid Added minMax #55

**Comment by mrinal07** [comment]
Can you please assign me?
I would love to do.

**Comment by SMITVASOYA** [comment]
can I try it?

**Comment by jayanthjj** [comment]
@Mrinal-Choudhary07 @SMITVASOYA It's done just left to be merged, try to solve other examples on https://edabit.com/challenge/ and open an issue with the template used above.
