### ISSUE TITLE
Next Prime

### ISSUE THREAD

**Issue by keshav304** [aayushi-droid/Edabit-Solutions#61]
Before jumping into Pr first comment for assign.

**Problem statement** : Given an integer, create a function that returns the next prime. If the number is prime, return the number itself.
**Probelm Link** : https://edabit.com/challenge/arobBz954ZDxkDC9M
**Choose one Cateorgy** - Hard
**question category** : math, numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
@aayushi-droid please assign

**Comment by priyansh-jain10** [comment]
Hey! I would like to give it a shot! Mind assigning it to me?

**Comment by keshav304** [comment]
Hey! @priyansh-jain10 you can choose any problem from [edabit](https://edabit.com/challenges) then create an issue and get it assigned and work on it.

**Comment by priyalHedau15** [comment]
hey @keshav304  could you assign this to me .I would like to give solution of this problem

**Comment by ashishrrs** [comment]
i would love to work on this

**Comment by sravyasri2001** [comment]
Assign it to me

**Comment by lucifer79gg** [comment]
I have completed this

**Comment by aayushi-droid** [comment]
#79
