### ISSUE TITLE
Prime Factorization of an Integer

### ISSUE THREAD

**Issue by keshav304** [aayushi-droid/Edabit-Solutions#63]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that returns a list containing the prime factors of whatever integer is passed to it.
**Probelm Link** : https://edabit.com/challenge/8vBvgJMc2uQJpD6d7
**Choose one Cateorgy** - Very Hard
**question category** :  maths, numbers

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by keshav304** [comment]
@aayushi-droid please assign

**Comment by prajjyadav** [comment]
Hi! @keshav304 can you assign this to me.. i would like to try

**Comment by Deepak290701** [comment]
I have submitted the PR can you please check .

**Comment by princekalra** [comment]
can u please assign it to me i am happy to contribute in this
