### ISSUE TITLE
Is it Time for Milk and Cookies?

### ISSUE THREAD

**Issue by Avn007** [aayushi-droid/Edabit-Solutions#69]
Before jumping into Pr first comment for assign.

**Problem statement** : Christmas Eve is almost upon us, so naturally we need to prepare some milk and cookies for Santa! Create a function that accepts a (year, month, day) of date and returns true if it's Christmas Eve (December 24th) and false otherwise. Keep in mind that month of Date is 0 based, meaning December is the 11th month while January is 0.
**Probelm Link** :  https://edabit.com/challenge/2XSQ56rSm47oH8fyF
**Choose one Cateorgy** - Very Easy
**question category** : dates, validation

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Avn007** [comment]
Hey @aayushi-droid , can you assign this to me?

**Comment by dev-abir** [comment]
please assign this to me

**Comment by NidhiNivedita6** [comment]
Please assign me this.
