### ISSUE TITLE
Minimum Removals to Make Two Strings Anagrams

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#7]
Before jumping into Pr first comment for assign.

**Problem statement:** Create a function that returns the smallest number of letter removals so that two strings are anagrams of each other.
**Probelm Link:** https://edabit.com/challenge/NBi75bkHrhTTxmxST

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vamsireddy22** [comment]
Can I work on this?

**Comment by aayushi-droid** [comment]
assigned @vamsireddy22 , 

Best of Luck,

**Comment by mrinal07** [comment]
I want to work on this.
Can u please assign me.
