### ISSUE TITLE
Longest Palindrome Subsequence

### ISSUE THREAD

**Issue by rishabhgarg25699** [aayushi-droid/Edabit-Solutions#71]
**Problem statement - Given a string s, find the longest palindromic subsequence's length in s. You may assume that the maximum length of s is 1000.** :
**Problem Link - https://leetcode.com/problems/longest-palindromic-subsequence/** : 
**Choose one Cateorgy  - Medium** 
**question category** :

**Comment by rishabhgarg25699** [comment]
Please assign this issue to me.

**Comment by shibrahmachari** [comment]
Please assign this issue to me.

**Comment by mohilkhare1708** [comment]
it wasn't assigned to me, but I've done it anyway, I'll appreciate it be being merged. PR #166

**Comment by sakshi0461** [comment]
Please assign this issue to me...

**Comment by sh-1010** [comment]
Assign it to me
