### ISSUE TITLE
Factorial of a Non-Negative Integer

### ISSUE THREAD

**Issue by priyalHedau15** [aayushi-droid/Edabit-Solutions#72]
Before jumping into Pr first comment for assign.

Problem statement : Factorial of a Non-Negative Integer
Write a function that takes a non-negative integer and return its factorial.

factorial(4) ➞ 24

factorial(0) ➞ 1

factorial(9) ➞ 362880

Problem Link : https://edabit.com/challenge/M3MZS3RHKZ67fQQBM
Choose one Category - Easy
question category : algorithms, math

---
Before submitting a PR please Check some details.

- [ ] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/

```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by priyalHedau15** [comment]
hey @aayushi-droid  could I work on this issue for hactorbest

**Comment by priyalHedau15** [comment]
hey @aayushi-droid  could I work on this issue for hacktoberfest

**Comment by ChaoticBlack** [comment]
Yo! I can do this immediately if assigned to me!

**Comment by ashishrrs** [comment]
i would love to work on this

**Comment by ViivekUV** [comment]
Hey! I'd like to contribute to this issue. Please assign it to me

**Comment by viren-vii** [comment]
Assign me

**Comment by shubhampal98** [comment]
I would like to get assigned to this task.

**Comment by damascus8** [comment]
Please assign me this task

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by nausher-ali** [comment]
please assign me this task would like to work on this

**Comment by Rahul171201** [comment]
pls assign me I am new to this community and want to start with such good first issues

**Comment by Tripathi-Alok** [comment]
please assign it to me

**Comment by Nusratillo777** [comment]
hello, Can you assign me?
