### ISSUE TITLE
An Ordered Matrix

### ISSUE THREAD

**Issue by kushalbargoti** [aayushi-droid/Edabit-Solutions#73]
Before jumping into Pr first comment for assign.

**Problem statement** : Create an ordered 2D array (matrix). A matrix is ordered if its (0, 0) element is 1, its (0, 1) element is 2, and so on. Your function needs to create an a × b matrix where a is the first argument and b is the second.
**Probelm Link** :  https://edabit.com/challenge/qbpHHZYQrJnNYjtjn
**Choose one Cateorgy** - Medium 
**question category** :  Arrays, Math

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck.

**Comment by kushalbargoti** [comment]
@aayushi-droid  Please Assign this issue to me :)

**Comment by Vrindagupta6828** [comment]
@kushalbargoti  please assign me this

**Comment by kushalbargoti** [comment]
Hey! @Vrindagupta6828  you can choose any problem from [edabit](https://edabit.com/challenges) then create an issue and get it assigned and work on it.

**Comment by ashishrrs** [comment]
I would love to work on this project

**Comment by RamyaThirumalaisamy** [comment]
@aayushi-droid  Please assign this task to me
Thanks!

**Comment by Vrindagupta6828** [comment]
@kushalbargoti when will these issues be assigned?

**Comment by babitha667** [comment]
I would like to contribute please assign this to me.

**Comment by kushalbargoti** [comment]
@aayushi-droid  Done✅

**Comment by ACAA06** [comment]
Problem statement : Create a function to find only the root value of x in any quadratic equation ax^2 + bx + c.
Probelm Link : https://edabit.com/challenge/nasKYub6qEAfQcFuy
Choose one Cateorgy - Medium
question category : Conditions , Math, Algebra

Can i do this in C++?
