### ISSUE TITLE
Matrix Transpose

### ISSUE THREAD

**Issue by kushalbargoti** [aayushi-droid/Edabit-Solutions#74]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that transposes a 2D matrix.
**Probelm Link** : https://edabit.com/challenge/4KaoDvxaFSmf38bPQ
**Choose one Cateorgy** - Medium 
**Question category** : Arrays, Math 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck.

**Comment by kushalbargoti** [comment]
@aayushi-droid  Please Assign this issue to me... I will do my best ..  :)

**Comment by KhushiGangopadhyay** [comment]
hey! can i work on this issue, i am new to hacktoberfest and would like to start with this

**Comment by kushalbargoti** [comment]
Hey @KhushiGangopadhyay you can choose another problem from [edabit](https://edabit.com/challenges) then create an issue and get it assigned and work on it.

**Comment by KhushiGangopadhyay** [comment]
ok thank you !

**Comment by bhandarii7** [comment]
please assign this issue to me. I like to start with this for hacktober fest

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by shreyraj2002** [comment]
Hey! please assign me this issue,
As I am having an experience of 3 years in C++ coding!

**Comment by aayushi-droid** [comment]
@kushalbargoti I have assigned to you a lot of problems. please give chance to new contributors.
Thanks

**Comment by kushalbargoti** [comment]
Okay thanks @aayushi-droid

**Comment by kushalbargoti** [comment]
@aayushi-droid Assign this problem to someone else.
