### ISSUE TITLE
XOR Swap Algorithm

### ISSUE THREAD

**Issue by SangeetaMishra** [aayushi-droid/Edabit-Solutions#75]
Before jumping into Pr first comment for assign.

**Problem statement** : Switch 2 variables using the XOR operator
**Probelm Link** :  https://edabit.com/challenge/dHYXiEXydZxrwntBq
**Choose one Cateorgy** - Medium
**question category** : Bit Operations, Language Fundamentals

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by SangeetaMishra** [comment]
@aayushi-droid  Please assign this to me

**Comment by ashishrrs** [comment]
Plzz assign this to me

**Comment by rgarg-2711** [comment]
I would like to work on this issue. Please assign it to me.
[XORSwap.txt](https://github.com/Py-Droid/Edabit-Solutions/files/5313578/XORSwap.txt)

**Comment by rgarg-2711** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by saks1209am** [comment]
Can you assign this issue to me?
