### ISSUE TITLE
Rectangle in Circle

### ISSUE THREAD

**Issue by SangeetaMishra** [aayushi-droid/Edabit-Solutions#76]
Before jumping into Pr first comment for assign.

**Problem statement** : Create a function that takes three numbers — the width and height of a rectangle, and the radius of a circle and returns if the rectangle can fit inside the circle
**Probelm Link** : https://edabit.com/challenge/PoSkat7FepavXW49T
**Choose one Cateorgy** - Medium 
**question category** : Geometry, Math, Validation

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by SangeetaMishra** [comment]
@aayushi-droid Please assign this to me

**Comment by ashishrrs** [comment]
Please assign this to me

**Comment by saurabhatram** [comment]
I can do this

**Comment by 23krishna** [comment]
@aayushi-droid please assign this task to me.
ThankYou

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by tusharkashyap63** [comment]
I'll be glad to work on this issue.

**Comment by Swarn10** [comment]
@aayushi-droid  and @SangeetaMishra  please assign this to me . I believe I will be able to do full justice to this problem.
