### ISSUE TITLE
Mini Peaks

### ISSUE THREAD

**Issue by SangeetaMishra** [aayushi-droid/Edabit-Solutions#77]
Before jumping into Pr first comment for assign.

**Problem statement** : Write a function that returns all the elements in an array that are strictly greater than their adjacent left and right neighbors.
**Probelm Link** :  https://edabit.com/challenge/5KAsvzdc9DLfEx65t
**Choose one Cateorgy** - Medium 
**question category** : Arrays, Loops

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by SangeetaMishra** [comment]
@aayushi-droid Please assign this to me

**Comment by ashishrrs** [comment]
I would like to work on this

**Comment by js0805** [comment]
I would love to work over this.

**Comment by shibrahmachari** [comment]
i would like to contribute to this, please assign?

**Comment by uditascloud** [comment]
please assign it to me. thank you

**Comment by amishaagarwal1998** [comment]
Please assign this to me! Thank you!

**Comment by alokgoldy** [comment]
please assign me

**Comment by Nusratillo777** [comment]
Please assign me

**Comment by vidit624** [comment]
Please assign me

**Comment by Swarn10** [comment]
Please assign this issue to me. I believe I would be able to do justice to this issue.

**Comment by riyagoel192** [comment]
Please assign this to me

**Comment by sakshi-negi123** [comment]
Please assign this to me.
