### ISSUE TITLE
Absolute Sum

### ISSUE THREAD

**Issue by ajitg1** [aayushi-droid/Edabit-Solutions#78]
Before jumping into Pr first comment for assign.

**Problem statement** : Take an array of integers (positive or negative or both) and return the sum of the absolute value of each element.
**Probelm Link** :  https://edabit.com/challenge/jBFpjEG3tvsjTZbD4
**Choose one Cateorgy** - Easy
**question category** :  arrays, loop, math, number

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ajitg1** [comment]
Hey @aayushi-droid, I would like to work on this issue, please assign this to me.

**Comment by vedanttttt** [comment]
Please assign it to me

**Comment by ghost** [comment]
Assign to me

**Comment by avishkar2001** [comment]
Please assign me this task

**Comment by shibrahmachari** [comment]
please assign

**Comment by sravyasri2001** [comment]
Please assign

**Comment by Sourabh-Kumar7** [comment]
Hey @aayushi-droid, I would like to work on this issue, please assign this to me.
