### ISSUE TITLE
Repeating Cycle

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#8]
Before jumping into Pr first comment for assign.

**Problem statement:** Below is an example of a repeating cycle.
```
isRepeatingCycle([1, 2, 3, 1, 2], 3) => true
// Since the first two elements of [1, 2, 3] equals [1, 2]
```
**Check Link for Full Question**
**Probelm Link:** https://edabit.com/challenge/q8aKKcukixHhcH7n4

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vamsireddy22** [comment]
Can I work on this?

**Comment by aayushi-droid** [comment]
@vamsireddy22 assigned,
Best of Luck,
