### ISSUE TITLE
Return the First element in array.

### ISSUE THREAD

**Issue by Harshit11072000** [aayushi-droid/Edabit-Solutions#83]
Before jumping into Pr first comment for assign.

**Problem statement** :Return the First element in array.
**Probelm Link** : https://edabit.com/challenge/QaApgtePE6QrCZ64o
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy, Hacktoberfest

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Harshit11072000** [comment]
Please Assign.

**Comment by sherwin2000** [comment]
please give me this issue

**Comment by amankothari1908** [comment]
Assign me i can solve with proper comment !!

**Comment by sidanand67** [comment]
I am willing to fix this issue.

**Comment by js0805** [comment]
Please assign me this one.

**Comment by sherwin2000** [comment]
did u assign it to me?

**Comment by ayushkumarmishra** [comment]
I wanted to help you for this one

**Comment by avishkar2001** [comment]
Please assign me. I can do within mins

**Comment by kajal1122** [comment]
assign this to me

**Comment by sravyasri2001** [comment]
Assing it to me please.

**Comment by NidhiNivedita6** [comment]
Please assign me this.
