### ISSUE TITLE
Less Than 100?

### ISSUE THREAD

**Issue by 0xamitdutta** [aayushi-droid/Edabit-Solutions#87]
Before jumping into Pr first comment for assign.

**Problem statement** : Less Than 100?
**Probelm Link** : https://edabit.com/challenge/9MjEpkL7yAjAqiH58
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Very Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by 0xamitdutta** [comment]
I would like to work on this

**Comment by devansh-pratap-singh** [comment]
I would like to solve this problem.

**Comment by VaderX** [comment]
can u assign this to me?

**Comment by meta-crusher** [comment]
@Amitdutta7 can u assign this to me?

**Comment by 0xamitdutta** [comment]
> @Amitdutta7 can u assign this to me?

Hey, I'm not the owner of the repo. You can ask to get assigned if you create a new issue of your own I guess. There are plenty of problem statements on the Edabit platform.

**Comment by meta-crusher** [comment]
ok

**Comment by NidhiNivedita6** [comment]
Please assign me this.
