### ISSUE TITLE
Mystery Challenge in Cpp

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/Edabit-Solutions#9]
Before jumping into Pr first comment for assign.

**Problem statement:** Write a function that takes an integer n and turns it into the ouput. No further instructions.
**Probelm Link:** https://edabit.com/challenge/RRX73DEm2BLp8z2TG

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by vamsireddy22** [comment]
Can I take this?

**Comment by aayushi-droid** [comment]
@vamsireddy22 Ya sure Go ahead.
