### ISSUE TITLE
Power Calculator

### ISSUE THREAD

**Issue by Halix267** [aayushi-droid/Edabit-Solutions#91]
Before jumping into Pr first comment for assign.

**Problem statement** :Power Calculator
**Probelm Link** : https://edabit.com/challenge/wAdE9te55cowBLcPs
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Easy

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will calculate power by given voltage and current
 * Problem Link : https://edabit.com/challenge/wAdE9te55cowBLcPs
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Halix267** [comment]
I would like to solve this problem .Plzz assign me this issue

**Comment by ashishrrs** [comment]
I would like to work over it.

**Comment by Halix267** [comment]
@ashishrrs  Plzz create your own issue

**Comment by viren-vii** [comment]
Assign this work to me!

**Comment by Zbillion** [comment]
Please assign this to me

**Comment by vortex2099** [comment]
Can you assign me this problem?
