### ISSUE TITLE
Area of triangle

### ISSUE THREAD

**Issue by ghost** [aayushi-droid/Edabit-Solutions#95]
Before jumping into Pr first comment for assign.

**Problem statement** : Write a function that takes the base and height of a triangle and return its area.
**Problem Link** : https://edabit.com/challenge/HvYiBXgfPtnDHitym
**Choose one Category** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : very easy

---
Before submitting a PR please Check some details.

- [ ] fileName format should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is valid for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by ghost** [comment]
Please let me work on this!

**Comment by BalajiG2000** [comment]
Can you assign this to me @devansh-pratap-singh

**Comment by hkrobotics** [comment]
i am up for this

**Comment by viren-vii** [comment]
Assign this to me

**Comment by NidhiNivedita6** [comment]
Please assign me this.
