### ISSUE TITLE
Letters Shared Between Two Words

### ISSUE THREAD

**Issue by ashishrrs** [aayushi-droid/Edabit-Solutions#98]
Before jumping into Pr first comment for assign.

Problem statement : Create a function that returns the number of characters shared between two words.
Probelm Link : https://edabit.com/challenge/qeCS48GXtK9NJLc9C
Choose one Cateorgy - Hard
Question category : Arrays,Strings

Before submitting a PR please Check some details.

 

- [ ] fileName formet should be in camelcase
      example- returnTheNextNumber.py
 

- [ ] Choose label for Problem , example- "good first issue", "easy"

- [ ] In file there should be problem statement and link to problem

/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/qeCS48GXtK9NJLc9C
*/
int main() {
    int bla;
    return 0;
}
This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck.

**Comment by viren-vii** [comment]
Please assign this to me
