### ISSUE TITLE
Split 25

### ISSUE THREAD

**Issue by div5252** [aayushi-droid/Edabit-Solutions#99]
Before jumping into Pr first comment for assign.

**Problem statement** : About a month ago I stumbled upon an interesting problem — something called the 25 split. In the problem, you had to break up 25 into parts, and, from those parts that add to it, try to create the biggest product.
**Probelm Link** :  https://edabit.com/challenge/PbtMHCLm83NwqSnnS
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** : Very Hard

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by milanj-1** [comment]
assign this to me

**Comment by keerti2001** [comment]
Plz assign this to me
